#include <vector>
#include <string>
#include <iostream>
#include <cstdio>
#include <stack>
#include <queue>
#include <algorithm>
#include <unordered_map>
#include <limits>
#include <set>
#include <unordered_set>
#include <numeric>
#include <cmath>
#include <charconv>
#include <regex>
#include <iomanip>
#include "ListNode.h"
#include "DoubleListNode.h"
using namespace std;